In [ ]:
import torch as tf
if tf.backends.mps.is_available():
    print("MPS is available. GPU acceleration is ready!")
    print(tf.__version__)
else:
    print("MPS not found. Running on CPU.")

MPS is available. GPU acceleration is ready!
2.10.0


## Creating a Tensor 

In [2]:
#scalar
scalar = tf.tensor(7)

#attributes of scalar
scalar.ndim


0

# Getting tensor back as int

In [3]:
scalar.item()

7

In [4]:
vector = tf.Tensor([7,7])
vector

tensor([7., 7.])

In [5]:
vector.shape

torch.Size([2])

In [6]:
MATRIX = tf.Tensor([[7,8],
                   [9,10]])
MATRIX.ndim

2

In [7]:
TENSOR = tf.Tensor([[[1,2,3],
                      [3,4,5],
                      [5,6,7]],
                      [[1,2,3],
                      [2,3,4],
                      [4,4,4]]])
TENSOR.ndim

3

In [8]:
TENSOR.shape

torch.Size([2, 3, 3])

# Rnadom Tensors 

In [9]:
random_tensor = tf.rand(3,4,3)
random_tensor

tensor([[[7.1452e-01, 1.4513e-01, 5.2583e-04],
         [9.6321e-01, 5.4924e-01, 5.3575e-01],
         [5.4259e-01, 5.9407e-01, 4.3231e-01],
         [2.4953e-01, 8.2665e-01, 4.5206e-01]],

        [[9.3813e-01, 8.8927e-01, 8.5148e-01],
         [9.5408e-01, 9.8340e-01, 6.1923e-02],
         [2.5227e-01, 8.6339e-01, 2.7140e-01],
         [2.2915e-01, 5.7102e-01, 9.8217e-02]],

        [[9.4052e-01, 7.6386e-01, 4.9543e-01],
         [8.2067e-01, 1.0261e-01, 4.4864e-01],
         [1.4415e-01, 3.1138e-01, 2.9358e-01],
         [2.6234e-01, 3.6533e-01, 8.9099e-01]]])

### creating tensor for the size of an image 

In [10]:
image_size_tensor = tf.rand(size=(224,243,3)) #height,width,color channels (R,G,B)
image_size_tensor

tensor([[[6.9579e-01, 2.2789e-01, 2.6192e-01],
         [3.8989e-01, 9.6857e-01, 1.5269e-01],
         [8.9415e-01, 2.7365e-01, 3.5163e-01],
         ...,
         [9.9238e-02, 8.7680e-01, 5.6394e-01],
         [6.9276e-01, 5.1691e-01, 7.7737e-01],
         [2.1241e-01, 4.4215e-01, 9.6369e-01]],

        [[8.0818e-01, 1.4168e-01, 5.5146e-01],
         [3.1204e-01, 1.5160e-02, 8.2841e-01],
         [6.8949e-01, 3.1990e-02, 8.7178e-01],
         ...,
         [7.5217e-01, 4.7415e-01, 3.7052e-01],
         [6.5018e-02, 4.8361e-01, 8.6511e-01],
         [1.4832e-01, 8.1821e-01, 5.6131e-01]],

        [[5.6559e-01, 7.6369e-01, 5.7695e-01],
         [4.2354e-01, 4.2520e-01, 4.0174e-01],
         [4.6043e-01, 2.2736e-01, 8.6296e-04],
         ...,
         [8.3970e-01, 7.9580e-01, 8.4076e-01],
         [5.7850e-01, 9.0069e-01, 2.2089e-01],
         [3.5095e-01, 6.8136e-01, 9.0630e-01]],

        ...,

        [[8.1155e-01, 5.7884e-01, 8.2782e-01],
         [4.5441e-01, 1.9044e-01, 1.8676e-02]

### zeros and ones

In [11]:
zeros = tf.zeros((2, 2))
zeros

tensor([[0., 0.],
        [0., 0.]])

In [12]:
one = tf.ones(3, 4)
one

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [13]:
hh = tf.arange(start=1,end=11,step=1,
                dtype=float,
                device=None,
                requires_grad=False)

In [14]:
ss = tf.zeros_like(hh)
ss

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=torch.float64)

In [15]:
new_ten = tf.tensor([3.0,6.0,9.0],
                    dtype=None,
                    device="mps",
                    requires_grad=False)
new_ten.dtype
new16_ten = new_ten.type(tf.float16)
new16_ten
new16_ten*new_ten

tensor([ 9., 36., 81.], device='mps:0')

In [17]:
some_ten = tf.rand(3,4,device="mps")

some_ten

tensor([[0.5385, 0.3843, 0.9547, 0.7942],
        [0.5465, 0.0068, 0.0642, 0.0926],
        [0.4397, 0.3763, 0.4646, 0.1167]], device='mps:0')

In [18]:
print(some_ten.dtype)
print(some_ten.shape)
print(some_ten.device)

torch.float32
torch.Size([3, 4])
mps:0


### manipluating tensors 

* addition
* subtraction 
* multiplication (element wise)
* division 
* matrix multiplication 


In [32]:
tens = tf.tensor([1,2,3,5],device="mps",dtype=tf.float32)
tens+10

tensor([11., 12., 13., 15.], device='mps:0')

In [21]:
tens*10

tensor([10, 30, 50])

In [22]:
tens/10

tensor([0.1000, 0.3000, 0.5000])

In [35]:
%%time
some_ten*tens

CPU times: user 1.29 ms, sys: 2.43 ms, total: 3.72 ms
Wall time: 18 ms


tensor([[0.5385, 0.7686, 2.8641, 3.9711],
        [0.5465, 0.0135, 0.1927, 0.4631],
        [0.4397, 0.7525, 1.3938, 0.5837]], device='mps:0')

In [42]:
%%time
tf.matmul(some_ten,tens)

CPU times: user 616 μs, sys: 301 μs, total: 917 μs
Wall time: 390 μs


tensor([8.1422, 1.2158, 3.1696], device='mps:0')

## to transpose

In [43]:
 tens.T

tensor([1., 2., 3., 5.], device='mps:0')

In [47]:
x = tf.arange(0,100,10,dtype=tf.float32)
x

tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [45]:
tf.min(x),tf.max(x)

(tensor(0), tensor(90))

In [48]:
tf.mean(x)

tensor(45.)

In [50]:
tf.sum(x)

tensor(450.)

In [52]:
tf.mode(x)

torch.return_types.mode(
values=tensor(0.),
indices=tensor(0))

In [53]:
tf.argmax(x)

tensor(9)

In [54]:
tf.argmin(x)

tensor(0)

## reshaping, stacking, squeezing and unsqueezing

* **reshape**: reshapes the tensor to the given shape
* **stack**: stacks the tensors along a new dimension like vstack and hstack
* **squeeze**: removes single-dimensional entries from the shape
* **unsqueeze**: adds a single-dimensional entry to the shape
* **view**: returns a view of the input with a specific shape
* **permute**: returns a view of the input with a specific permutation of dimensions

In [56]:
y = tf.arange(1., 13.)
y.shape,y

(torch.Size([12]),
 tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]))

while reshaping the tensors should be compatible

In [58]:
y.reshape(4, 3)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])

In [59]:
y.view(3,4)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

changing view changes the orignal tensor as they share the same memory


In [61]:
y_stacked = tf.stack([y,y,y,y], dim=0)
y_stacked

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])

squeeze removes dimensions of size 1

In [70]:
x = tf.squeeze(y)
x.ndim

1

unsqueeze adds a new dimension to the tensor at the dimention mentioned

In [69]:
tf.unsqueeze(x,dim=0).ndim


2

In [71]:
x_org = tf.rand(size =(224,224,3))
x_org.shape

torch.Size([224, 224, 3])

In [80]:
x_org[0,0,1]=100
print(x_org[0,0,1])
x_per = x_org.permute(0, 2, 1) #shift the axis 0->0 1->2 2->1
x_per.shape

tensor(100.)


torch.Size([224, 3, 224])

## random seed 

In [82]:
RANDOM_SEED = 42
tf.manual_seed(RANDOM_SEED)
gg = tf.rand(3,4)
tf.manual_seed(RANDOM_SEED)
yy = tf.rand(3,4)
print(gg==yy)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [86]:
tf.mps.device_count()

1