In [2]:
import torch as tf
if tf.backends.mps.is_available():
    print("MPS is available. GPU acceleration is ready!")
    print(tf.__version__)
else:
    print("MPS not found. Running on CPU.")

MPS is available. GPU acceleration is ready!
2.10.0


## Creating a Tensor 

In [3]:
#scalar
scalar = tf.tensor(7)

#attributes of scalar
scalar.ndim


0

# Getting tensor back as int

In [4]:
scalar.item()

7

In [5]:
vector = tf.Tensor([7,7])
vector

tensor([7., 7.])

In [6]:
vector.shape

torch.Size([2])

In [7]:
MATRIX = tf.Tensor([[7,8],
                   [9,10]])
MATRIX.ndim

2

In [8]:
TENSOR = tf.Tensor([[[1,2,3],
                      [3,4,5],
                      [5,6,7]],
                      [[1,2,3],
                      [2,3,4],
                      [4,4,4]]])
TENSOR.ndim

3

In [9]:
TENSOR.shape

torch.Size([2, 3, 3])

# Rnadom Tensors 

In [10]:
random_tensor = tf.rand(3,4,3)
random_tensor

tensor([[[0.9207, 0.1629, 0.7554],
         [0.7599, 0.6316, 0.2572],
         [0.9106, 0.4364, 0.0596],
         [0.6657, 0.9313, 0.8392]],

        [[0.9151, 0.7183, 0.5374],
         [0.7567, 0.3669, 0.2542],
         [0.3257, 0.2803, 0.9553],
         [0.9283, 0.4467, 0.7408]],

        [[0.8386, 0.5406, 0.6790],
         [0.2136, 0.9109, 0.3522],
         [0.9339, 0.1737, 0.5562],
         [0.1540, 0.5031, 0.5936]]])

### creating tensor for the size of an image 

In [11]:
image_size_tensor = tf.rand(size=(224,243,3)) #height,width,color channels (R,G,B)
image_size_tensor

tensor([[[8.8180e-01, 2.0605e-04, 4.3214e-01],
         [3.8196e-02, 9.0241e-01, 9.0281e-02],
         [4.2959e-01, 8.1272e-01, 3.5300e-01],
         ...,
         [7.6852e-01, 7.8357e-01, 9.9164e-01],
         [7.3882e-01, 4.9740e-02, 8.2952e-01],
         [7.8061e-01, 5.5605e-01, 8.8090e-02]],

        [[3.3445e-01, 3.0371e-01, 9.7271e-01],
         [7.3029e-01, 6.6333e-02, 7.9504e-01],
         [3.0032e-01, 9.7185e-01, 5.9200e-01],
         ...,
         [8.8805e-01, 1.1201e-01, 1.9496e-01],
         [2.9088e-01, 6.5570e-01, 4.3293e-01],
         [5.5218e-01, 2.3304e-01, 2.7711e-01]],

        [[2.4251e-02, 2.6818e-02, 1.7204e-01],
         [3.0173e-01, 3.6252e-01, 9.7498e-01],
         [1.6663e-01, 6.7393e-01, 8.5598e-01],
         ...,
         [3.4036e-01, 1.3595e-01, 5.6526e-01],
         [1.2869e-01, 2.5283e-01, 8.0721e-01],
         [2.0003e-01, 3.2865e-01, 3.7644e-01]],

        ...,

        [[9.6646e-01, 7.4080e-01, 2.1053e-01],
         [4.0212e-01, 7.4629e-01, 2.1601e-01]

### zeros and ones

In [12]:
zeros = tf.zeros((2, 2))
zeros

tensor([[0., 0.],
        [0., 0.]])

In [15]:
one = tf.ones(3, 4)
one

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [33]:
hh = tf.arange(start=1,end=11,step=1,
                dtype=float,
                device=None,
                requires_grad=False)

In [24]:
ss = tf.zeros_like(hh)
ss

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=torch.float64)

In [35]:
new_ten = tf.tensor([3.0,6.0,9.0],
                    dtype=None,
                    device="mps",
                    requires_grad=False)