In [1]:
import torch as tf
if tf.backends.mps.is_available():
    print("MPS is available. GPU acceleration is ready!")
    print(tf.__version__)
else:
    print("MPS not found. Running on CPU.")

MPS is available. GPU acceleration is ready!
2.10.0


## Creating a Tensor 

In [2]:
#scalar
scalar = tf.tensor(7)

#attributes of scalar
scalar.ndim


0

# Getting tensor back as int

In [3]:
scalar.item()

7

In [4]:
vector = tf.Tensor([7,7])
vector

tensor([7., 7.])

In [5]:
vector.shape

torch.Size([2])

In [7]:
MATRIX = tf.Tensor([[7,8],
                   [9,10]])
MATRIX.ndim

2

In [ ]:
TENSOR = tf.Tensor([[[1,2,3],
                      [3,4,5],
                      [5,6,7]],
                      [[1,2,3],
                      [2,3,4],
                      [4,4,4]]])
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([2, 3, 3])

# Rnadom Tensors 

In [18]:
random_tensor = tf.rand(3,4,3)
random_tensor

tensor([[[0.8735, 0.5529, 0.3824],
         [0.7665, 0.1650, 0.2765],
         [0.8580, 0.1506, 0.9988],
         [0.5308, 0.5588, 0.4341]],

        [[0.7718, 0.8622, 0.3172],
         [0.6077, 0.6383, 0.7495],
         [0.8787, 0.4307, 0.0298],
         [0.6374, 0.2794, 0.8738]],

        [[0.4131, 0.9459, 0.8855],
         [0.3901, 0.7190, 0.8443],
         [0.7322, 0.1077, 0.5904],
         [0.0967, 0.1619, 0.1744]]])