In [1]:
import torch as tf
if tf.backends.mps.is_available():
    print("MPS is available. GPU acceleration is ready!")
    print(tf.__version__)
else:
    print("MPS not found. Running on CPU.")

MPS is available. GPU acceleration is ready!
2.10.0


## Creating a Tensor 

In [2]:
#scalar
scalar = tf.tensor(7)

#attributes of scalar
scalar.ndim


0

# Getting tensor back as int

In [3]:
scalar.item()

7

In [4]:
vector = tf.Tensor([7,7])
vector

tensor([7., 7.])

In [5]:
vector.shape

torch.Size([2])

In [7]:
MATRIX = tf.Tensor([[7,8],
                   [9,10]])
MATRIX.ndim

2

In [ ]:
TENSOR = tf.Tensor([[[1,2,3],
                      [3,4,5],
                      [5,6,7]],
                      [[1,2,3],
                      [2,3,4],
                      [4,4,4]]])
TENSOR.ndim

3

In [13]:
TENSOR.shape

torch.Size([2, 3, 3])