In [1]:
%pip install gensim

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 42.6 MB/s eta 0:00:0000:0100:01


In [2]:
import gensim.downloader as api
model = api.load('word2vec-google-news-300')

[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [3]:
model['dog']

array([ 5.12695312e-02, -2.23388672e-02, -1.72851562e-01,  1.61132812e-01,
       -8.44726562e-02,  5.73730469e-02,  5.85937500e-02, -8.25195312e-02,
       -1.53808594e-02, -6.34765625e-02,  1.79687500e-01, -4.23828125e-01,
       -2.25830078e-02, -1.66015625e-01, -2.51464844e-02,  1.07421875e-01,
       -1.99218750e-01,  1.59179688e-01, -1.87500000e-01, -1.20117188e-01,
        1.55273438e-01, -9.91210938e-02,  1.42578125e-01, -1.64062500e-01,
       -8.93554688e-02,  2.00195312e-01, -1.49414062e-01,  3.20312500e-01,
        3.28125000e-01,  2.44140625e-02, -9.71679688e-02, -8.20312500e-02,
       -3.63769531e-02, -8.59375000e-02, -9.86328125e-02,  7.78198242e-03,
       -1.34277344e-02,  5.27343750e-02,  1.48437500e-01,  3.33984375e-01,
        1.66015625e-02, -2.12890625e-01, -1.50756836e-02,  5.24902344e-02,
       -1.07421875e-01, -8.88671875e-02,  2.49023438e-01, -7.03125000e-02,
       -1.59912109e-02,  7.56835938e-02, -7.03125000e-02,  1.19140625e-01,
        2.29492188e-01,  

In [4]:
model.most_similar(positive=['dog','woman'],negative=['man'],topn=5)

[('dogs', 0.7394188642501831),
 ('puppy', 0.7249194979667664),
 ('pit_bull', 0.6649513244628906),
 ('miniature_poodle', 0.6646480560302734),
 ('pet', 0.6521182656288147)]

In [5]:
model.similarity('fire','ice')

np.float32(0.105000705)

In [6]:
import torch

In [7]:
input_ids = torch.tensor([2,3,5,1])
input_ids.shape

torch.Size([4])

In [ ]:
model.distance('king','queen')

np.float32(0.3489043)

In [9]:
model['king']

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  

In [10]:
vocab_size = 50257
output_dim =256

torch.manual_seed(0)
embedding_layer = torch.nn.Embedding(vocab_size, output_dim)

In [11]:
print(embedding_layer(torch.tensor([5])))

tensor([[-3.4592e-01,  6.2020e-01,  6.9225e-01,  7.4497e-01, -9.2998e-01,
         -6.8485e-01,  6.3002e-01,  1.9448e+00,  3.8837e-01,  8.8457e-01,
         -1.1058e+00, -1.1974e+00,  1.4020e+00,  4.9731e-01,  6.7992e-01,
          1.1085e+00,  8.0650e-01, -1.5344e-01, -2.7453e-01,  2.8552e-01,
          1.0041e+00, -1.1813e+00,  1.6745e+00, -1.7934e+00, -1.2959e+00,
         -8.0705e-01,  2.1192e+00,  3.5834e-01,  3.4515e-01, -1.8560e-01,
         -1.5892e-01,  1.2183e+00, -1.1200e+00, -4.5884e-01, -1.2930e+00,
          1.0784e+00,  1.1637e-01,  2.6903e-01, -1.8819e+00, -5.4570e-01,
          2.2222e-01, -2.8869e-01,  6.6929e-01,  1.4945e+00,  2.4317e-02,
         -4.9781e-01,  7.3783e-01,  1.2763e+00, -1.5469e-01, -2.8457e-01,
         -6.2964e-01, -2.4856e-01,  8.0565e-01, -1.1019e+00, -7.4083e-01,
          8.2408e-01, -9.5033e-01,  6.5933e-01, -6.8629e-01, -2.9166e-01,
          1.8699e+00, -1.1054e+00, -1.4418e-01, -3.4626e-01,  8.2239e-01,
          9.4072e-01, -2.2081e+00,  4.

In [ ]:
import ssl
import certifi
import tiktoken
from torch import D
from urllib.request import urlopen

context = ssl.create_default_context(cafile=certifi.where())
url = "https://raw.githubusercontent.com/GavinGongTech/LLM-From-Scratch/refs/heads/main/the-verdict.txt"
file_path = "the-verdict.txt"
with urlopen(url, context=context) as response:
    verdict = response.read().decode("utf-8")
with open(file_path, "w") as file:
    file.write(verdict)

In [15]:
with open("the-verdict.txt", "r", encoding="utf-8") as f:
    raw_text = f.read()

In [18]:
import torch 
from torch.utils.data import Dataset, DataLoader

In [19]:
class GPTDatasetV1(Dataset):
    def __init__(self, txt, tokenizer, max_length, stride):
        self.input_ids = []
        self.target_ids = []

        token_ids = tokenizer.encode(txt, allowed_special={"<|endoftext|>"})
        for i in range(0, len(token_ids) - max_length, stride):
            input_chunk = token_ids[i : i + max_length]
            target_chunk = token_ids[i + 1 : i + max_length + 1]
            self.input_ids.append(torch.tensor(input_chunk))
            self.target_ids.append(torch.tensor(target_chunk))

    def __len__(self):
        return len(self.input_ids)

    def __getitem__(self, idx):
        return self.input_ids[idx], self.target_ids[idx]

In [16]:
def create_dataloader_v1(txt, batch_size=4, max_length=256, 
                         stride=128, shuffle=True, drop_last=True,
                         num_workers=0):

    tokenizer = tiktoken.get_encoding("gpt2")

    dataset = GPTDatasetV1(txt, tokenizer, max_length, stride)

    dataloader = DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=shuffle,
        drop_last=drop_last,
        num_workers=num_workers
    )

    return dataloader

In [20]:
max_length =4
dataloder = create_dataloader_v1(raw_text, batch_size=8, max_length=max_length, stride=max_length)
data_iter = iter(dataloder)
input_ids, target_ids = next(data_iter)
print("Input IDs:\n", input_ids)
print("Target IDs:\n", target_ids)

Input IDs:
 tensor([[   13,  8759,  2763,   438],
        [   11,   290,  1816,   866],
        [  284,  1064,   503,  1521],
        [   11,  2087,   329,   616],
        [  286, 32315, 12606,  9074],
        [  568,   340,   373,   645],
        [ 1522,   502,    13,  1320],
        [ 2376, 26927,   616,   670]])
Target IDs:
 tensor([[ 8759,  2763,   438,  1169],
        [  290,  1816,   866,   290],
        [ 1064,   503,  1521,    13],
        [ 2087,   329,   616, 35957],
        [32315, 12606,  9074,    13],
        [  340,   373,   645,  1049],
        [  502,    13,  1320,   338],
        [26927,   616,   670,   526]])


# batch size : 8 
# max context length :4
## makes a vector of 8x4
and a dim of 256 for each embedding 
## make a vector of 8x4x256

# for positional embedding 
## context length of 4 and dim for each embedding so 
## 4x256 is the size for the positional embedding 

In [21]:
context_length = max_length
pos_embedding_layer = torch.nn.Embedding(context_length, output_dim)

In [22]:
pos_embedding = pos_embedding_layer(torch.arange(context_length))
print("Positional Embeddings:\n", pos_embedding)

Positional Embeddings:
 tensor([[ 0.2622,  0.3008, -0.9968,  ...,  0.4018, -0.9568, -0.4577],
        [ 0.0143,  2.0074,  0.7900,  ..., -0.8851,  0.4023,  0.6870],
        [-1.0412, -0.3501,  1.0060,  ..., -0.7935, -0.1178,  0.1919],
        [ 0.5343,  0.7589, -0.2145,  ..., -0.0861, -0.4651,  2.1439]],
       grad_fn=<EmbeddingBackward0>)


In [23]:
input_embeddings = pos_embedding+embedding_layer(input_ids)
print("Input Embeddings:\n", input_embeddings)

Input Embeddings:
 tensor([[[ 3.2791e-01,  5.8039e-01, -2.0765e+00,  ..., -7.7811e-01,
          -5.4944e-01, -8.2233e-02],
         [-1.3293e+00,  2.2521e+00,  2.6861e+00,  ..., -2.4969e-01,
          -5.4383e-02,  1.8034e+00],
         [-3.4632e-01, -2.2963e+00,  5.7777e-01,  ...,  2.8819e-01,
           5.3997e-02,  5.5678e-02],
         [ 7.2305e-01,  5.8463e-01, -1.8032e+00,  ..., -4.5742e-02,
          -6.7124e-01,  3.1707e+00]],

        [[ 5.4750e-01,  2.3216e-01, -1.0264e+00,  ..., -2.3619e-01,
          -2.1281e+00, -1.2993e+00],
         [ 1.7546e+00,  1.2363e+00,  5.8819e-01,  ..., -1.9351e+00,
           3.6136e-01, -1.2982e+00],
         [-2.7127e+00,  1.2979e+00, -5.5159e-01,  ..., -1.5442e+00,
           5.4160e-01,  7.3241e-01],
         [ 8.1119e-01,  2.4183e+00, -1.7354e+00,  ...,  1.2182e+00,
           9.9630e-01,  2.3378e+00]],

        [[ 1.8189e+00,  8.7220e-01, -3.6766e+00,  ...,  1.3210e+00,
          -9.0289e-01, -1.4045e+00],
         [-8.3609e-01,  2.6756e+